# Find egl project

# This module defines
#   EGL_INCLUDE_DIRS: jmixin headers
#   EGL_LIBRARIES: jmixin libraries
#   EGL_DEFINITIONS: some definitions
#
#   EGL_FOUND, If false, do not try to use EGL.

pkg_check_modules(LIBXCB REQUIRED xcb)
pkg_check_modules(LIBX11XCB REQUIRED x11-xcb)
pkg_check_modules(LIBEGL REQUIRED egl)
pkg_check_modules(LIBGLESV2 REQUIRED glesv2)
pkg_check_modules(LIBGL REQUIRED gl)
pkg_check_modules(LIBGLU REQUIRED glu)

if (${LIBXCB_FOUND} AND ${LIBX11XCB_FOUND} AND ${LIBEGL_FOUND} AND ${LIBGLESV2_FOUND} AND ${LIBGL_FOUND} AND ${LIBGLU_FOUND})
  set (EGL_INCLUDE_DIRS ${LIBXCB_INCLUDE_DIR} ${LIBX11XCB_INCLUDE_DIRS} ${LIBEGL_INCLUDE_DIRS} ${LIBGLESV2_INCLUDE_DIRS} ${LIBGL_INCLUDE_DIRS} ${LIBGLU_INCLUDE_DIRS})
  set (EGL_CFLAGS_OTHER ${LIBXCB_CFLAGS_OTHER} ${LIBX11XCB_CFLAGS_OTHER} ${LIBEGL_CFLAGS_OTHER} ${LIBGLESV2_CFLAGS_OTHER} ${LIBGL_CFLAGS_OTHER} ${LIBGLU_CFLAGS_OTHER})
  set (EGL_CFLAGS ${LIBXCB_CFLAGS} ${LIBX11XCB_CFLAGS} ${LIBEGL_CFLAGS} ${LIBGLESV2_CFLAGS} ${LIBGL_CFLAGS} ${LIBGLU_CFLAGS})

  set (EGL_LIBRARY_DIRS ${LIBXCB_LIBRARY_DIRS} ${LIBX11XCB_LIBRARY_DIRS} ${LIBEGL_LIBRARY_DIRS} ${LIBGLESV2_LIBRARY_DIRS} ${LIBGL_LIBRARY_DIRS} ${LIBGLU_LIBRARY_DIRS})
  set (EGL_LDFLAGS_OTHER ${LIBXCB_LDFLAGS_OTHER} ${LIBX11XCB_LDFLAGS_OTHER} ${LIBEGL_LDFLAGS_OTHER} ${LIBGLESV2_LDFLAGS_OTHER} ${LIBGL_LDFLAGS_OTHER} ${LIBGLU_LDFLAGS_OTHER})
  set (EGL_LDFLAGS ${LIBXCB_LDFLAGS} ${LIBX11XCB_LDFLAGS} ${LIBEGL_LDFLAGS} ${LIBGLESV2_LDFLAGS} ${LIBGL_LDFLAGS} ${LIBGLU_LDFLAGS})

  set (EGL_LIBRARIES ${LIBXCB_LIBRARIES} ${LIBX11XCB_LIBRARIES} ${LIBEGL_LIBRARIES} ${LIBGLESV2_LIBRARIES} ${LIBGL_LIBRARIES} ${LIBGLU_LIBRARIES} glut)

  set (EGL_FOUND "YES")
endif()

