# Find egl project

# This module defines
#   EGL_INCLUDE_DIRS: jmixin headers
#   EGL_LIBRARIES: jmixin libraries
#   EGL_DEFINITIONS: some definitions
#
#   EGL_FOUND, If false, do not try to use EGL.

set(ENV{PKG_CONFIG_PATH} "$ENV{PKG_CONFIG_PATH}:/opt/vc/lib/pkgconfig")

pkg_check_modules(LIBEGL REQUIRED brcmglesv2)
pkg_check_modules(LIBBCMHOST REQUIRED bcm_host)

if (${LIBEGL_FOUND} AND ${LIBBCMHOST_FOUND})
  set (EGL_INCLUDE_DIRS ${LIBEGL_INCLUDE_DIR} ${LIBBCMHOST_INCLUDE_DIRS})
  set (EGL_CFLAGS_OTHER ${LIBEGL_CFLAGS_OTHER} ${LIBBCMHOST_CFLAGS_OTHER})
  set (EGL_CFLAGS ${LIBEGL_CFLAGS} ${LIBBCMHOST_CFLAGS})

  set (EGL_LIBRARY_DIRS ${LIBEGL_LIBRARY_DIRS} ${LIBBCMHOST_LIBRARY_DIRS})
  set (EGL_LDFLAGS_OTHER ${LIBEGL_LDFLAGS_OTHER} ${LIBBCMHOST_LDFLAGS_OTHER})
  set (EGL_LDFLAGS ${LIBEGL_LDFLAGS} ${LIBBCMHOST_LDFLAGS})

  set (EGL_LIBRARIES ${LIBEGL_LIBRARIES} ${LIBBCMHOST_LIBRARIES})

  set (EGL_FOUND "YES")
endif()

